### PR TITLE
WordPress Applience auto updater function

### PR DESCRIPTION
**Pull request by jeroenpeters1986**
In these changes I've:
 - removed a few plugins which were not maintained or availabe anymore
 - added plugins which fill the gap of the removed plugins
 - tweaked a few php.ini settings (bigger upload/post values)
 - added the FS_DIRECT update method in wp-config.php
 - added php5-curl install (required for some plugins like jetpack)

Please:
 - verify this setup is safe
 - check the versioning of the changelog, I could not find any guidelines
 - leave me feedback if there is something that needs improvement, this is my first run at TKLdev

What I've tested after the installation:
 - upload media
  - cropping pictures
 - upload an old plugin by uploading a .zip
  - updating this plugin by the autoupdater
 - install a plugin from wordpress repository
 - install a theme from wordpress repository
 - used the default WordPress export & import script to verify media and upload handling

### CODE REVIEW

**Comment by JedMeister** [comment]
Hi @jeroenpeters1986 FWIW [this](https://github.com/turnkeylinux/tracker/blob/master/GITFLOW.rst#make-your-changes) is the preferred  way to go (i.e. from what I can see; pretty much like you've done except with your changes in a new branch rather than `master`...). @alonswartz may let you get away with it this time (I'll leave that to him to decide) but please keep the TKL gitflow in mind for future reference.

FWIW too if you think that this commit closes the bug (issue) then please say so. E.g. something like:

"closes /turn/turnkeylinux/tracker/issues/173" (assuming that you think it does - otherwise please ignore my comment...)

Finally, please don't take offence to my comments. We really appreciate contributions and at a glance it looks like a great way to go! Good work! :+1:

**Comment by jeroenpeters1986** [comment]
Hi @JedMeister, thank you for the tips! I forgot about the branching. I'm not that familiair with GitHub and mentioning bugs/issues just yet. I'll wait for Alon and see if I get a free pass this time haha.

If this works I might also do other appliances, and I surely will keep the GITFLOW.rst in mind. Thanks for pointing me in the right direction :)

**Comment by JedMeister** [comment]
You are most welcome :)

**Comment by lirazsiri** [comment]
Best pull request ever. Amazing work.

**Comment by jeroenpeters1986** [comment]
Hi @lirazsiri, thank you for the compliment about the work. I hope this will get a nice new image going.  I'm currently working on a little Django app, when that's finished, I'll be picking a new target. Thanks for checking my work and merging it!

**Pull request merged**
