### PR TITLE
Enter user name at install (turnkeylinux/tracker#444)

### PR DESCRIPTION
**Pull request by jeroenpeters1986**
Users are now able to enter a desired username in the WordPress install wizard. This resolves turnkeylinux/tracker#444

### CODE REVIEW

**Comment by jeroenpeters1986** [comment]
Extra info: Using tkldev I built this appliance and successfully installed WordPress with a custom username :) Logging in with that username at wp-admin worked liked a charm

**Comment by JedMeister** [comment]
Thanks for the PR @jeroenpeters1986 but I'm not sure that this will make it into v14.0. We are suffering from so much feature creep already and we are sooo overdue for the release it's just not funny...! See how we go...

**Comment by jeroenpeters1986** [comment]
@JedMeister Don't worry! It's OK if this is gonna be in a later release. Also thanks for applying labels to turnkeylinux/tracker#444 I couldn't :(

**Comment by jeroenpeters1986** [comment]
@alonswartz I'm not sure what closed means. It states that my branch has unmerged commits. Shall I update and do this in a new branch after the 14.0 is released?

**Comment by alonswartz** [comment]
@jeroenpeters1986 yeah, sorry for not adding a comment. We are finalizing 14.0 and will need to target this for 14.1.

We might also want to think about doing this for all appliances across the board, not just wordpress...

**Comment by jeroenpeters1986** [comment]
No worries @alonswartz, I will be saving them and submit them again when 14.0 has been finalized. I can also check if I can implement this at more installs, althought it might not be possible overwhere.

**Comment by JedMeister** [comment]
I'm reopening this but not merging for now.

**Pull request closed without merging**
